name: authors
port: 30002
deployment:
  replicas: 3
  env:
    NOTIFY_QUEUE: "NOTIFY_QUEUE"
    CREATE_AUTHOR_QUEUE: "CREATE_AUTHOR_QUEUE"

authService: auth-service
public:
  - path: "/ping"
    method: "GET"
    id: "GET_PING"

  - path: "/health"
    method: "GET"
    id: "GET_HEALTH"

  - path: "/api/author/[a-z]*[^/]+$"
    method: "GET"
    id: "GET_AUTHOR"
    prefix: "~ ^"

  - path: "/api/author"
    method: "GET"
    id: "GET_AUTHORS"
